#!/usr/bin/python3

try:
    print(x)
except:
    print("x is not defined")
finally:
    print("the try-except code has been executed")
